name: Examples tests

on:
  pull_request_target:
    branches:
      - master
  workflow_dispatch:

jobs:
  Integration_tests:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3
        with:
            repository: ${{ github.event.pull_request.head.repo.full_name }}
            ref: ${{ github.event.pull_request.head.ref }}
      - uses: outscale-dev/frieza-github-actions/frieza-clean@master
        with:
          access_key: ${{ secrets.OSC_ACCESS_KEY }}
          secret_key: ${{ secrets.OSC_SECRET_KEY }}
          region: ${{ secrets.OSC_REGION }}
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Run Examples
        run: make test-examples
        env:
          OUTSCALE_ACCESSKEYID: ${{ secrets.OSC_ACCESS_KEY }}
          OUTSCALE_SECRETKEYID: ${{ secrets.OSC_SECRET_KEY }}
          OUTSCALE_REGION: ${{ secrets.OSC_REGION }}
